= Metanorma IETF samples

image:https://github.com/metanorma/mn-samples-ietf/workflows/ubuntu/badge.svg["Build Status", link="https://github.com/metanorma/mn-samples-ietf/actions?workflow=ubuntu"]
image:https://github.com/metanorma/mn-samples-ietf/workflows/macos/badge.svg["Build Status", link="https://github.com/metanorma/mn-samples-ietf/actions?workflow=macos"]
image:https://github.com/metanorma/mn-samples-ietf/workflows/windows/badge.svg["Build Status", link="https://github.com/metanorma/mn-samples-ietf/actions?workflow=windows"]
image:https://github.com/metanorma/mn-samples-ietf/workflows/docker/badge.svg["Build Status", link="https://github.com/metanorma/mn-samples-ietf/actions?workflow=docker"]

This document is available in its rendered forms here:

* https://metanorma.github.io/mn-samples-ietf/[Metanorma IETF samples (HTML)]


== Fetching the document

[source,sh]
----
git clone https://github.com/metanorma/mn-samples-ietf/
----

== Installing Build Tools

See https://www.metanorma.com/author/topics/install/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker
version by:

[source,sh]
----
export METANORMA_DOCKER=1
----

The `Makefile` will automatically choose the proper command to
execute.


== Building The Document

[source,sh]
----
make clean all
----

The following outputs will be built:

* Metanorma XML (https://github.com/metanorma/metanorma-model-iso) (`[filename].xml`)
* RFC XML v3 (`[filename].rfc.xml`)
* HTML (`[filename].html`)
* TXT (`[filename].txt`)


== Iterating the document

[source,sh]
----
make html
open *.html
----


== Notes

WARNING: RFC XML v2 is no longer supported by Metanorma.

The Metanorma-IETF v2 documents provided here are purely for reference:

* `sources/antioch-v2/document.adoc`
* `sources/example-v2/document.adoc`
