= Metanorma IETF samples

image:https://github.com/metanorma/mn-samples-ietf/workflows/generate/badge.svg["Build Status", link="https://github.com/metanorma/mn-samples-ietf/actions?workflow=generate"]
image:https://github.com/metanorma/mn-samples-ietf/workflows/docker/badge.svg["Build Status", link="https://github.com/metanorma/mn-samples-ietf/actions?workflow=docker"]

This document is available in its rendered forms here:

* https://metanorma.github.io/mn-samples-ietf/[Metanorma IETF samples (HTML)]


== Fetching the document

[source,sh]
----
git clone https://github.com/metanorma/mn-samples-ietf/
----

== Installing Build Tools

See https://www.metanorma.com/author/topics/install/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker:

[source,sh]
----
docker run -v "$(pwd)":/metanorma -w /metanorma -it metanorma/mn metanorma site generate --agree-to-terms
----


== Building The Document

[source,sh]
----
metanorma site generate --agree-to-terms
----


The following outputs will be built:

* Metanorma XML (https://github.com/metanorma/metanorma-model-iso) (`[filename].xml`)
* RFC XML v3 (`[filename].rfc.xml`)
* HTML (`[filename].html`)
* TXT (`[filename].txt`)


== Iterating the document

[source,sh]
----
metanorma site generate --agree-to-terms
open site/index.html
----


== DEPRECATED DOCUMENTS

WARNING: RFC XML v2 is no longer supported by Metanorma.

These Metanorma-IETF v1 documents provided here are purely for reference, and can only be run with metanorma-ietf 1.x.x with older xml2rfc installations:

* `sources/antioch-v2/document.adoc`
* `sources/example-v2/document.adoc`
